### ISSUE TITLE
[BE Feat] Create Email backend service using Resend

### ISSUE THREAD

**Issue by SherRao** [KonferCA/SPUR-Onboard#214]
## Checklist
Before submitting this ticket, make sure this ticket:
- [x] Is **labelled properly** - if this is a refactor, add the label!
- [x] Has the **SPUR project assigned to it**.
- [x] Has an **assigned milestone**.

And lastly:
- [ ] Once someone picks up this ticket, **make sure to assign it**.

## Description
MIgrate the old account using accounts@konfer.ca

**Comment by juancwu** [comment]
Scope change: the intact email service should work just fine but the verification email could use some work, so I will be making it look better.
