### ISSUE TITLE
[BE Feat] Create file upload backend service

### ISSUE THREAD

**Issue by SherRao** [KonferCA/SPUR-Onboard#215]
## Checklist
Before submitting this ticket, make sure this ticket:
- [x] Is **labelled properly** - if this is a refactor, add the label!
- [x] Has the **SPUR project assigned to it**.
- [x] Has an **assigned milestone**.

And lastly:
- [x] Once someone picks up this ticket, **make sure to assign it**.

## Description
Make use of public functions such as UploadFile(content []byte) to make the update from AWS to other interfaces easier later

**Comment by juancwu** [comment]
Upon closer inspection of the current existing code, there is no need to update the currently storage package so will be closing this issue
