### ISSUE TITLE
[BE Feat] Setup and create common shared data structures and objects

### ISSUE THREAD

**Issue by SherRao** [KonferCA/SPUR-Onboard#217]
## Checklist
Before submitting this ticket, make sure this ticket:
- [x] Is **labelled properly** - if this is a refactor, add the label!
- [x] Has the **SPUR project assigned to it**.
- [x] Has an **assigned milestone**.

And lastly:
- [ ] Once someone picks up this ticket, **make sure to assign it**.

## Description
These are various constants, errors, helpers, responses, and requests that can be reused through the backend.

### Constants
- [ ] x

### Errors
- [ ] x

### Helpers
- [ ] x

### Responses
- [ ] x

### Requests
- [ ] x

**Comment by juancwu** [comment]
These are values in the server package. So we can just create empty files. For requests and responses, these are meant to be super generic structs that any route can just use.
